name: disambg
channels:
  - pytorch
  - nvidia
  - huggingface
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.11.9
  - pip=24.2
  - jupyter=1.0.0
  - jupyterlab=4.2.5
  - notebook=7.2.2
  - ipywidgets=8.1.5
  - pandas=2.2.2
  - numpy=1.26.4
  - scipy=1.13.1
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - nltk=3.8.1
  - pytorch=2.4.0
  - torchvision=0.19.0
  - torchaudio=2.4.0
  - pytorch-cuda=12.4.0
  - pybind11=2.13.5
  - scikit-learn=1.5.1
  - wordcloud=1.9.3
  - accelerate=0.34.0
  - transformers=4.44.2
  - sentence-transformers=3.0.1
  - datasets=2.21.0
  - pyarrow=17.0.0
  - pip:
      - python-dotenv==1.0.1
      - openai==1.43.0
      - wandb==0.17.8
      - tiktoken==0.7.0
      - python-bidi==0.4.2
      - arabic-reshaper==3.0.0
      - emoji==1.4.2
      - arabert==1.0.1
      - Arabic-Stopwords==0.4.3
      - fasttext==0.9.3
      - tabulate==0.9.0
      - rich[jupyter]==13.8.0
      - stanza==1.8.2
      - tqdm==4.66.5
